const mongoose = require('mongoose')
const Schema = mongoose.Schema

const PriceSchema = new Schema({
	product: {
		type: String,
		require: true,
	},
	price: {
		type: String,
		require: true,
	},
	he_name: {
		type: String,
		require: true,
	},
	ru_name: {
		type: String,
		require: true,
	},
	en_name: {
		type: String,
		require: true,
	},
	he_description: {
		type: [String],
		require: true,
	},
	ru_description: {
		type: [String],
		require: true,
	},
	en_description: {
		type: [String],
		require: true,
	},
	tag: {
		type: String,
		require: true,
	},
	recommended: {
		type: String,
		require: true,
	},
})

PriceSchema.index({ product: 'text' })

const Price = mongoose.model('price', PriceSchema)

// var price = [
// 	{
// 		product: 'salad_gambrinus',
// 		price: '50',
// 		he_name: 'סלט גמברינוס',
// 		ru_name: 'Салат Гамбринус',
// 		en_name: 'Gambrinus Salad',
// 		he_description: ['מלפפון,עגבניה,חסה,בצל וגבינה בולגרית מעל'],
// 		ru_description: ['огурец, помидор, листья салата, лук и болгарский сыр'],
// 		en_description: [
// 			'Cucumber, tomato, lettuce, onion and fetta cheese on top',
// 		],
// 		tag: 'starters',
// 	},
// 	{
// 		product: 'chips_gambrinus',
// 		price: '25/30',
// 		he_name: 'צ׳יפס גמברינוס',
// 		ru_name: 'Чипс Гамбринус',
// 		en_name: 'Gambrinus Chips',
// 		he_description: [
// 			'קוביות תפוח אדמה עם גבינה בולגרית מעל',
// 			'אופציות: גבינה מעל,גבינה בצד,גבינה רק על חצי',
// 		],
// 		ru_description: [
// 			'Картофель нарезанный кубиками с болгарским сыром сверху',
// 			'Варианты: сыр сверху, сыр на стороне, сыр только на половину',
// 		],
// 		en_description: [
// 			'Diced potatoes with fetta cheese on top',
// 			'Options: cheese on top, cheese on the side, cheese only on half',
// 		],
// 		tag: 'starters',
// 	},
// 	{
// 		product: 'mukram',
// 		price: '50',
// 		he_name: 'תפוח אדמה ברוטב שמנת פטריות מוקרם',
// 		ru_name: 'Картофель в "мундире" с грибным соусом В печи',
// 		en_name: 'Boiled potato(skin-on) with creamy mushroom sauce',
// 		he_description: ['תפוח אדמה אפוי פרוס עם רוטב שמנת פטריות מוקרם'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'starters',
// 	},
// 	{
// 		product: 'pitriyot',
// 		price: '50',
// 		he_name: 'פטריות ברוטב שמנת עם גבינה',
// 		ru_name: 'Грибы в сливочном соусе с сыром',
// 		en_name: 'Mushroom with creamy cheese sauce',
// 		he_description: ['פטריות טריות שמפניון ברוטב שמנת עם גבינה'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'starters',
// 	},
// 	{
// 		product: 'toast',
// 		price: '35',
// 		he_name: 'טוסט גמברינוס/טוסט עם מבחר תוספות',
// 		ru_name: 'Тост гамбринус/Тост с добавками',
// 		en_name: 'Gambrinus Toast / Toast with toppings',
// 		he_description: [
// 			'טוסט גבינה ומעל רוטב שמנת פטריות, טוסט עם תוספות לבחירה',
// 			'עגבניה, בצל, בולגרית, פטריות',
// 			'עד 3 תוספות לבחירה *',
// 		],
// 		ru_description: [''],
// 		en_description: [
// 			'Optional toppings : tomato ,fetta cheese ,mushroom, onion',
// 			'*up to 3 toppings',
// 		],
// 		tag: 'starters',
// 	},
// 	{
// 		product: 'mix',
// 		price: '130',
// 		he_name: 'מיקס שרימפס וקלמרי',
// 		ru_name: 'Микс креветки и кальмары',
// 		en_name: 'Fried breaded shrimp/calamri mix',
// 		he_description: ['מוגש מטוגן בשמן עמוק עם רוטב בית בצד'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'mevushal',
// 		price: '50',
// 		he_name: 'שרימפס מבושל 500גר׳',
// 		ru_name: 'Креветки варёныe 500г',
// 		en_name: 'Cooked shrimp (shell on) 500g',
// 		he_description: ['מבושל במים , שלמים לא מקולפים, מוגש עם רוטב בית'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'mahvat',
// 		price: '75',
// 		he_name: 'שרימפס בחמאה ושום',
// 		ru_name: 'Креветки в чесночном соусе',
// 		en_name: 'Garlic butter shrimps',
// 		he_description: ['מוגש עם לחם'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: '',
// 		price: '75',
// 		he_name: 'שרימפס / קלמרי ״על האש״ פיקנטי',
// 		ru_name: 'Креветки кальмары на вертеле ״острые״',
// 		en_name: 'Grilled Spicy shrimp/calamri',
// 		he_description: ['שתי שיפודים לבחירה , אופציות חריף,לא חריף'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'metugan',
// 		price: '75',
// 		he_name: 'שרימפס מטוגן',
// 		ru_name: 'Креветки в сухарях жареные во фритюре',
// 		en_name: 'Fried breaded shrimps',
// 		he_description: ['שרימפס מצופה בפירורי לחם מטוגן בשמן עמוק'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'kalamari',
// 		price: '75',
// 		he_name: 'קלמרי מטוגן',
// 		ru_name: 'Кальмары в сухарях жареные во фритюре',
// 		en_name: 'Fried breaded calamari',
// 		he_description: ['קלמרי חצוי מצופה בפירורי לחם ומטוגן בשמן עמוק'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'krabi',
// 		price: 'out of stock',
// 		he_name: 'סרטן הים 1ק״ג',
// 		ru_name: 'Крабы морские варёныe 1кг',
// 		en_name: 'Boiled crab 1kg',
// 		he_description: ['סרטנים שלמים חצויים לא מקולפים'],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'raki',
// 		price: 'out of stock',
// 		he_name: 'סרטן הנהרות 1ק״ג',
// 		ru_name: 'Раки 1кг',
// 		en_name: 'Crayfish 1kg',
// 		he_description: [''],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'seafood',
// 	},
// 	{
// 		product: 'denis_fried',
// 		price: '95',
// 		he_name: 'דניס מטוגן בשמן עמוק',
// 		ru_name: 'Дэнис во фритюре',
// 		en_name: 'Fried sea bream',
// 		he_description: ['מוגש עם סלט, צ׳יפס קוביות וחמאה'],
// 		ru_description: ['подается с чипсами ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'denis_oven',
// 		price: '95',
// 		he_name: 'דניס בתנור',
// 		ru_name: 'Дэнис в печи',
// 		en_name: 'Oven baked sea bream',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'lavrak_oven',
// 		price: '125',
// 		he_name: 'לברק בתנור',
// 		ru_name: 'Сибас в печи',
// 		en_name: 'Oven baked seabass',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'lavrak_fried',
// 		price: '125',
// 		he_name: 'לברק מטוגן בשמן עמוק',
// 		ru_name: 'сибас во фритюре',
// 		en_name: 'Fried seabass',
// 		he_description: ['מוגש עם סלט, צ׳יפס וחמאה'],
// 		ru_description: ['подается с чипсами ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'bananot',
// 		price: '95',
// 		he_name: 'דגי ים מטוגנים 500גר׳',
// 		ru_name: 'Жареные морские рыбки 500г',
// 		en_name: 'Fried small sea fish 500g',
// 		he_description: ['מוגש עם סלט, צ׳יפס קוביות וחמאה'],
// 		ru_description: ['подается с чипсами ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'forel',
// 		price: '95',
// 		he_name: 'פורל מעושן בתנור',
// 		ru_name: 'Форель копчёный в печи 500г',
// 		en_name: 'Oven baked smoked trout',
// 		he_description: ['מוגש עם סלט, תפו״א'],
// 		ru_description: ['подается с картошкой ,салатом и соусом'],
// 		en_description: [''],
// 		tag: 'fish',
// 	},
// 	{
// 		product: 'netah',
// 		price: '150',
// 		he_name: 'נתח קצבים עד 500גר׳',
// 		ru_name: 'Телятина вырезка 500г',
// 		en_name: 'Butchers steak 500g',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'boded_kaful',
// 		price: '100/170',
// 		he_name: 'אנטריקוט מיושן 350/650גר׳',
// 		ru_name: 'Телятина Антрекот 350/650г',
// 		en_name: 'Aged Argentinian Entrecote 350/650g',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'boded_kaful_tanur',
// 		price: '100/170',
// 		he_name: 'אנטריקוט בתנור 350/650גר׳',
// 		ru_name: 'Антрекот в печи 350/650г',
// 		en_name: 'Oven roasted Entrecote 350/650g',
// 		he_description: ['אנטריקוט ברוטב מעל בצל ושמיר , מוגש עם סלט,תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'spareribs',
// 		price: 'out of stock',
// 		he_name: 'צלעות לבן – ספריבס 900גר׳',
// 		ru_name: 'Рёбрышки свиные сперибс 900г',
// 		en_name: 'Grilled Spareribs 900g',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'lavan',
// 		price: '100',
// 		he_name: 'סטייק צוואר לבן 700גר׳',
// 		ru_name: 'Свиная шейная часть 700г',
// 		en_name: 'Pork shoulder steam 700g',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'file_boded_kaful',
// 		price: '100/150',
// 		he_name: 'פילה לבן בתנור 450/950גר׳',
// 		ru_name: 'Филе свиное в печи 450/950г',
// 		en_name: 'Oven roasted pork fillet 450/950g',
// 		he_description: ['פילה ברוטב מעל בצל ושמיר , מוגש עם סלט,תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'keves',
// 		price: '100',
// 		he_name: 'צלעות טלה 500גר׳',
// 		ru_name: 'Рёбрышки бараньи 500г',
// 		en_name: 'Lamb chops 500g',
// 		he_description: ['מוגש עם סלט, תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'naknikiyot',
// 		price: '70',
// 		he_name: 'נקנקיות טלה ״על האש״',
// 		ru_name: 'Колбаски из баранины "На гриле"',
// 		en_name: 'Grilled lamb irish sausages',
// 		he_description: ['שתי נקניקיות לא חריפות, מוגש עם סלט , תפו״א וחמאה'],
// 		ru_description: ['подается с картошкой ,салатом ,соусом и маслом'],
// 		en_description: [''],
// 		tag: 'meat',
// 	},
// 	{
// 		product: 'chaser12',
// 		price: '12',
// 		he_name: 'צייסר הבית - ג׳ימסון',
// 		ru_name: 'Чейсер JAMESON',
// 		en_name: 'Ceaser - JAMESON',
// 		he_description: [''],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'beer_0.3_0.5',
// 		price: '28/30',
// 		he_name: 'בירה 0.3/0.5',
// 		ru_name: 'Пиво 0.3/0.5',
// 		en_name: 'Beer 0.3/0.5',
// 		he_description: [''],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'beer_0',
// 		price: '20',
// 		he_name: 'בירה 0%',
// 		ru_name: 'Пиво 0%',
// 		en_name: 'Beer 0%',
// 		he_description: ['הייניקן 0%'],
// 		ru_description: ['Heineken 0%'],
// 		en_description: ['Heineken 0%'],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'wine',
// 		price: '35/120',
// 		he_name: 'יין',
// 		ru_name: 'Вино',
// 		en_name: 'Wine',
// 		he_description: [
// 			'VillaWolf יין לבן - גוורצטרמינר',
// 			'RECANATI Yasmin Red יין אדום - קברנה סובניון ומרלו',
// 		],
// 		ru_description: [
// 			'Белое вино - Gewurztraminer VillaWolf',
// 			'Красное вино - Каберне Совиньон и Мерло RECANATI Yasmin Red',
// 		],
// 		en_description: [
// 			'White wine - Gewurztraminer VillaWolf',
// 			'Red wine - Cabernet Sauvignon and Merlot RECANATI Yasmin Red',
// 		],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'kala',
// 		price: '15',
// 		he_name: 'שתייה קלה',
// 		ru_name: 'Холодные напитки',
// 		en_name: 'Cold Drinks',
// 		he_description: [
// 			'קוקה קולה,קוקה קולה זירו,ספרייט',
// 			'ספרייט זירו,מירנדה,סודה,מי טוניק',
// 			'לא מוגז : תפוזים (פריגת) , לימונענע (פריגת) , חמוציות ',
// 			', עגבניות. לא סחוט , מוגש בכוס',
// 		],
// 		ru_description: [
// 			'Coca-Cola, Coca-Cola Zero, Sprite,Sprite Zero, Miranda, содовая, Tonic',
// 			'Без газа: Апельсиновый (пригат),клюквенный,лимонад (пригат),Томатный,Минеральная вода.',
// 			'Все соки не выжатые и подаются в стакане.',
// 		],
// 		en_description: [
// 			'Coca-Cola, Coca-Cola Zero, 7up, 7up zero, Miranda, soda, Tonic',
// 			'Mineral water,Orange(prigat),lemonade(prigat),cranberry,tomato',
// 		],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'hama',
// 		price: '12',
// 		he_name: 'שתייה חמה',
// 		ru_name: 'Горячие напитки',
// 		en_name: 'Hot Drinks',
// 		he_description: ['אספרסו / תה נענע , לימון'],
// 		ru_description: ['Эспрессо ,Чай (мята,лимон)'],
// 		en_description: ['Espresso, Tea (lemon,mint)'],
// 		tag: 'beverage',
// 	},
// 	{
// 		product: 'irish',
// 		price: '20',
// 		he_name: 'אייריש קפה',
// 		ru_name: 'Айриш кофе',
// 		en_name: 'Irish Coffee',
// 		he_description: ['אספרסו עם תמצית אייריש'],
// 		ru_description: ['Эспрессо с ирландским Ликёром'],
// 		en_description: ['Espresso with irish liquor'],
// 		tag: 'bevarage',
// 	},
// 	{
// 		product: 'takila_based',
// 		price: '45',
// 		he_name: 'על בסיס טקילה',
// 		ru_name: 'На основе текилы',
// 		en_name: 'Tequila based',
// 		he_description: [
// 			'״מרגריטה בטעמים״',
// 			'תות/פטל',
// 			'״טקילה סאן ראיס״',
// 			'טקילה,תפוז',
// 		],
// 		ru_description: [
// 			'"Маргарита со вкусом"',
// 			'Клубника / Малина',
// 			'"Текила Сан Раис"',
// 			'Текила, Апельсин',
// 		],
// 		en_description: [
// 			'"Flavored Margarita"',
// 			'Strawberry / Raspberry',
// 			'"Tequila Sun Rais"',
// 			'Tequila, Orange',
// 		],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'vodka_based',
// 		price: '45',
// 		he_name: 'על בסיס וודקה',
// 		ru_name: 'На основе водки',
// 		en_name: 'Vodka based',
// 		he_description: [
// 			'״רפסודיה״',
// 			'וודקה,שנאפס אפרסק,פטל,תפוז,לימון',
// 			'״לונג-איילנד״',
// 			'וודקה,רום,ג׳ין,טקילה,קולה',
// 			'״קוברה״',
// 			'וודקה,רום,ג׳ין,טקילה,תפוז',
// 			'״וונדר-לאנד״',
// 			'וודקה,מי סודה,ליים',
// 			'״אפל-טיני״',
// 			'וודקה,שנאפס תפוח,לימון,תפוח',
// 			'״בלאק-ראשן״',
// 			'וודקה,ליקר קפה',
// 			'״קוסמופוליטן״',
// 			'וודקה,חמוציות,שנאפס אפרסק',
// 			'״בלודי מרי״',
// 			'וודקה, מיץ עגבניות,לימון',
// 		],
// 		ru_description: [
// 			'"Рапсодия"',
// 			'Водка, персиковый шнапс, малина, апельсин, лимон',
// 			'"Лонг-Айленд"',
// 			'Водка, ром, джин, текила, кола',
// 			'"Кобра"',
// 			'Водка, ром, джин, текила, апельсин',
// 			'"wonderland"',
// 			'Водка, газированная вода, лайм',
// 			'"Apple-Tini"',
// 			'Водка, яблочный шнапс, лимон, яблоко',
// 			'"Black Russian"',
// 			'Водка, кофейный ликер',
// 			'"Cosmopolitan"',
// 			'Водка, клюква, персиковый шнапс',
// 			'"Кровавая Мэри"',
// 			'Водка, томатный сок, лимон',
// 		],
// 		en_description: [
// 			'"Rhapsody"',
// 			'Vodka, peach schnapps, raspberry, orange, lemon',
// 			'"Long Island"',
// 			'Vodka, rum, gin, tequila, cola',
// 			'"Cobra"',
// 			'Vodka, rum, gin, tequila, orange',
// 			'"Wonderland"',
// 			'Vodka, soda water, lime',
// 			'"Apple-Tini"',
// 			'Vodka, apple schnapps, lemon, apple',
// 			'"Black Russian"',
// 			'Vodka, coffee liqueur',
// 			'"Cosmopolitan"',
// 			'Vodka, cranberries, peach schnapps',
// 			'"Bloody Mary"',
// 			'Vodka, tomato juice, lemon',
// 		],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'gin_based',
// 		price: '45',
// 		he_name: 'על בסיס ג׳ין',
// 		ru_name: 'На основе джина',
// 		en_name: 'Gin based',
// 		he_description: ['״סאן פרנסיסקו״', 'ג׳ין,ליקר בננה,תפוז'],
// 		ru_description: ['"Сан-Франциско"', 'джин, банановый ликер, апельсин'],
// 		en_description: ['"San Francisco"', 'gin, banana liqueur, orange'],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'campari_based',
// 		price: '45',
// 		he_name: 'על בסיס קמפרי',
// 		ru_name: 'На основе Кампари',
// 		en_name: 'Campari based',
// 		he_description: ['״קמפרי״', 'מיץ תפוזים/סודה'],
// 		ru_description: ['"Кампари"', 'Апельсиновы сок / сода'],
// 		en_description: ['"Campari"', 'Orange juice / Soda'],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'rum_based',
// 		price: '45',
// 		he_name: 'על בסיס רום',
// 		ru_name: 'На основе рома',
// 		en_name: 'Rum based',
// 		he_description: [
// 			'״מוחיטו״',
// 			'רום,נענע,לימון',
// 			'״דאיקירי״',
// 			'רום,לימון+ תות/פטל',
// 		],
// 		ru_description: [
// 			'"Мохито"',
// 			'Ром, мята, лимон',
// 			'"Дайкири"',
// 			'ром, лимон + клубника / малина',
// 		],
// 		en_description: [
// 			'"Mojito"',
// 			'Rum, mint, lemon',
// 			'"Daikiri"',
// 			'rum, lemon + strawberry / raspberry',
// 		],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'shament_based',
// 		price: '45',
// 		he_name: 'על בסיס שמנת מתוקה',
// 		ru_name: 'на основе сливок',
// 		en_name: 'based on Heavy Cream',
// 		he_description: [
// 			'״אורגזמה״',
// 			'בייליס,ליקר קפה,שמנת מתוקה,חלב',
// 			'״פרפקט ליידי״',
// 			'בייליס,ליקר קפה,שמנת מתוקה,סאוטארן קומפורט',
// 			'״וויט ראשן״',
// 			'וודקה,ליקר קפה,שמנת מתוקה',
// 		],
// 		ru_description: [
// 			'"Оргазм"',
// 			'Baileys, кофейный ликер, сливки, молоко',
// 			'"Perfect Lady"',
// 			'Baileys, кофейный ликер, сливки, Southern Comfort',
// 			'"White Russian"',
// 			'Водка, кофейный ликер, сливки',
// 		],
// 		en_description: [
// 			'"Orgasm"',
// 			'Baileys, coffee liqueur, sweet cream, milk',
// 			'"Perfect Lady"',
// 			'Baileys, coffee liqueur, sweet cream, Southern Comfort',
// 			'"White Russian"',
// 			'Vodka, coffee liqueur, sweet cream',
// 		],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'whiskey_based',
// 		price: '55',
// 		he_name: 'על בסיס וויסקי',
// 		ru_name: 'На основе виски',
// 		en_name: 'Whiskey based',
// 		he_description: [
// 			'״הסנדק״',
// 			'ויסקי,אמרטו',
// 			'״ראסטי-נייל״',
// 			'ויסקי,דראמבוי',
// 			'״סאואר״',
// 			'ויסקי/רום/טקילה',
// 		],
// 		ru_description: [
// 			'"The Godfather"',
// 			'Виски, Амаретто',
// 			'"Rusty-Nail"',
// 			'Виски, Драмбой',
// 			'"sour"',
// 			'Виски / Ром / Текила',
// 		],
// 		en_description: [
// 			'"The Godfather"',
// 			'Whiskey, Amaretto',
// 			'"Rusty-Nail"',
// 			'Whiskey, Drumboy',
// 			'"sour"',
// 			'Whiskey / Rum / Tequila',
// 		],
// 		tag: 'cocktails',
// 	},
// 	{
// 		product: 'nutella',
// 		price: '35',
// 		he_name: 'פאי קרם אגוזים / עוגת שוקולד נוטלה',
// 		ru_name: 'Ореховый пай / нутелла торт',
// 		en_name: 'Walnut cream pie / Nutella sponge cake',
// 		he_description: [''],
// 		ru_description: [''],
// 		en_description: [''],
// 		tag: 'desserts',
// 	},
// 	{
// 		product: 'glida',
// 		price: '15',
// 		he_name: 'גלידה ״בן & גריס״',
// 		ru_name: 'Мороженое Ben & Jerry`s',
// 		en_name: 'Ben and Jerry`s ice cream',
// 		he_description: [
// 			'שוקולד בראוניס - גלידת שוקולד עם חתיכות בראוניס',
// 			'בצק עוגיות - גלידת וניל עם בצק עוגיות שוקולד צ`יפס',
// 			'קרם עוגיות - גלידת שמנת משובחת עם עוגיות במילוי קרם וניל',
// 			'צ`אנקי מנקי® - גלידת שמנת משובחת עם בננות , חתיכות פאדג` ואגוזי מלך',
// 			'דולצ`ה דה לצ`ה - גלידת שמנת משובחת עם ריבת חלב ופאדג',
// 		],
// 		ru_description: [
// 			'Chocolate Brownies - шоколадное мороженое с кусочками пирожных',
// 			'Cookie Dough - ванильное мороженое с шоколадным тестом для печенья',
// 			'Cookie Cream - изысканное мороженое с кремом и печеньем, наполненное ванильным кремом',
// 			'Chunky Manky® - изысканное сливочное мороженое с бананами, кусочками помадки и грецкими орехами',
// 			'Dolce de Leche - нежное сливочное мороженое с молочным джемом и помадой',
// 		],
// 		en_description: [
// 			'Chocolate Brownies - Chocolate ice cream with pieces of brownies',
// 			'Cookie Dough - Vanilla ice cream with chocolate chip cookie dough',
// 			'Cookie Cream - Fine Cream Ice Cream with Cookies Filled with Vanilla Cream',
// 			'Chunky Manky® - Fine Cream Ice Cream with Bananas, Fudge Pieces and Walnuts',
// 			'Dolce de Leche - Fine cream ice cream with milk jam and fudge',
// 		],
// 		tag: 'desserts',
// 	},
// ]
// save multiple documents to the collection referenced by Book Model
// Price.collection.insertMany(price, function (err, docs) {
// 	if (err) {
// 		return console.error(err)
// 	} else {
// 		console.log('Multiple documents inserted to Collection')
// 	}
// })
module.exports = Price
